import { View, Button, Text, StyleSheet } from "react-native";
import Buttonmaker from "./Buttonmaker";
export default function TestButtons({ style }) {
    return (
        <View style={[style, { backgroundColor: "#222" }]}>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
            <Buttonmaker></Buttonmaker>
        </View>
    );
}
